# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CICD

on:
  push:
    branches: ["main"]
    paths:
      - "client/*"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: sudo apt-get install npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start
