name: Frontend

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        working-directory: client

      - name: Build
        run: npm run build --if-present
        working-directory: client

      - name: Start the application
        run: npm start
        working-directory: client
